[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
  command = "npm run build"
  publish = "dist"
  environment = { 
    VITE_CLIENT_ID = "df90fdb9d3344593a2336d24346a515a",
    VITE_REDIRECT_URI = "https://gregory-vinokur-yandex-file-uploader.netlify.app",
    VITE_BASE_PATH = "/yandex-disk/"
  }